### PR TITLE
added a 'howhot' command to fun

### PR DESCRIPTION
**Pull request by shtabbbe**
A howhot command will return a random percent of how it

its a fun command ;)

### CODE REVIEW

**Comment by AlexFlipnote** [comment]
I would rather use `random.seed()` because it would be a bit more random but still consistent on each call.
```py
import random
ramdom.seed(user.id)
r = random.randint(1, 50)
hot = r / 1.17
await ctx.send(f"User is {hot:.2f}% hot")
```
and then some heart that is decided on how high the random.seed is

**Comment by perryprog** [comment]
Yeah that's a lot better, thanks

**Comment by shtabbbe** [comment]
I updated it to include a seed, this was quick thing I did in the middle of class, didn't expect this much attention thats why its a little sloppy

**Comment by AlexFlipnote** [comment]
I see, I'll merge it soon and improve it just a bit more if that's fine.

**Comment by shtabbbe** [comment]
Yep thats fine, just trying to make a little contribution, do whatever you feel neccessary

**Pull request merged**
